apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-09-28T19:27:23Z"
  generation: 1
  labels:
    app: stakater-backend
  name: stakater-backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stakater-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stakater-backend
    spec:
      containers:
        - image: jay4smile/stakater-backend
          imagePullPolicy: Never
          name: stakater-backend
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              value: "Stakater"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
